package com.spoofer.ui.theme

import androidx.compose.ui.graphics.Color

// Google-like Material 3 color palette

fun darkColorScheme() =
    androidx.compose.material3.darkColorScheme(
        primary = Color(0xFF8AB4F8),
        onPrimary = Color(0xFF002D69),
        primaryContainer = Color(0xFF1A73E8),
        onPrimaryContainer = Color(0xFFD3E3FD),
        secondary = Color(0xFF81C995),
        onSecondary = Color(0xFF00391C),
        secondaryContainer = Color(0xFF1E8E3E),
        onSecondaryContainer = Color(0xFFE6F4EA),
        tertiary = Color(0xFFF28B82),
        onTertiary = Color(0xFF601410),
        tertiaryContainer = Color(0xFFD93025),
        onTertiaryContainer = Color(0xFFFCE8E6),
        error = Color(0xFFF28B82),
        onError = Color(0xFF601410),
        errorContainer = Color(0xFF8C1D18),
        onErrorContainer = Color(0xFFFCE8E6),
        background = Color(0xFF202124),
        onBackground = Color(0xFFE8EAED),
        surface = Color(0xFF202124),
        onSurface = Color(0xFFE8EAED),
        surfaceVariant = Color(0xFF3C4043),
        onSurfaceVariant = Color(0xFF9AA0A6),
        outline = Color(0xFF5F6368),
        outlineVariant = Color(0xFF3C4043),
        surfaceDim = Color(0xFF171717),
        surfaceBright = Color(0xFF3C4043),
        surfaceContainerLowest = Color(0xFF000000),
        surfaceContainerLow = Color(0xFF1F1F1F),
        surfaceContainer = Color(0xFF202124),
        surfaceContainerHigh = Color(0xFF303134),
        surfaceContainerHighest = Color(0xFF3C4043),
        inverseSurface = Color(0xFFE8EAED),
        inverseOnSurface = Color(0xFF202124),
        inversePrimary = Color(0xFF1A73E8),
    )

fun lightColorScheme() =
    androidx.compose.material3.lightColorScheme(
        primary = Color(0xFF1A73E8),
        onPrimary = Color.White,
        primaryContainer = Color(0xFFD3E3FD),
        onPrimaryContainer = Color(0xFF041E49),
        secondary = Color(0xFF1E8E3E),
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFE6F4EA),
        onSecondaryContainer = Color(0xFF0D3C1A),
        tertiary = Color(0xFFD93025),
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFFFCE8E6),
        onTertiaryContainer = Color(0xFF601410),
        error = Color(0xFFD93025),
        onError = Color.White,
        errorContainer = Color(0xFFFCE8E6),
        onErrorContainer = Color(0xFF601410),
        background = Color(0xFFFFFFFF),
        onBackground = Color(0xFF202124),
        surface = Color(0xFFFFFFFF),
        onSurface = Color(0xFF202124),
        surfaceVariant = Color(0xFFF1F3F4),
        onSurfaceVariant = Color(0xFF5F6368),
        outline = Color(0xFFDADCE0),
        outlineVariant = Color(0xFFF1F3F4),
        surfaceDim = Color(0xFFE8EAED),
        surfaceBright = Color(0xFFFFFFFF),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF8F9FA),
        surfaceContainer = Color(0xFFF1F3F4),
        surfaceContainerHigh = Color(0xFFE8EAED),
        surfaceContainerHighest = Color(0xFFDADCE0),
        inverseSurface = Color(0xFF202124),
        inverseOnSurface = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFF8AB4F8),
    )
